### ISSUE TITLE
Allow to declare custom definitions

### ISSUE THREAD

**Issue by thomasvargiu** [elie29/zend-di-config#27]
It would be useful a config key which allows to set custom service definitions.

Something like:
```
return [
    'dependencies' => [
        'definitions' => [
            MyClass::class => DI\create(MyClass::class)->lazy(),
        ],
    ],
];
```

This will allow to use a configuration to define services in different modules when you use a modular structure.

**Comment by elie29** [comment]
@thomasvargiu thank you for the proposal.

Do you want to do it so I assigne it to you?

**Comment by elie29** [comment]
It occurs changes in: config, tests and Readme file

**Comment by thomasvargiu** [comment]
@elie29 I could work on it. It's a missed feature, a reason why I tried php-di to move then back to zend-servicemanager with zend-di AoT.

I have just a question. I think IMHO that something not related to map zend-servicemanger configuration to php-di should be moved in another configuration key. What do you think?

**Comment by elie29** [comment]
Well you are totally right. dependencies keys are mapped to zend service manager (except autowires). So we can have defintions key at the same level of dependencies and not inside it.

**Comment by elie29** [comment]
```php
return [
  'definitions' => [
    MyClass::class => DI\create(MyClass::class)->lazy(),
  ],
  'dependencies' => [],
];
```

**Comment by thomasvargiu** [comment]
`definitions` is a common key. In the last years projects are using namespace keys as configuration key, so it would be better to use a class namespace to use as a key to avoid conflicts, something like:

```php
return [
    Zend\DI\Config::class => [
        'definitions' => [],
    ],
];
```

But I think we should resolve #28 first, that's why I open it.

**Comment by elie29** [comment]
Right! should we need for definitions inside the classname key?
