### ISSUE TITLE
Zend\Di namespace

### ISSUE THREAD

**Issue by xtreamwayz** [elie29/zend-di-config#31]
Hi, I've been merging a related PR for zend-expressive today. I noticed you use the Zend\DI namespace for this package. It's a bit confusing since there is actually a [zend-di](https://github.com/zendframework/zend-di) package. There are no plans yet to add Zend\Di to the zend-expressive skeleton yet, but that might change in the future and which would introduce a namespace collision.

I'm wondering if you could change the namespace in a next major release to prevent confusion and a possible future namespace collision. Something like `Zend\PHPDI\`, `DI\` or `Ellie\DI\` would work.

**Comment by elie29** [comment]
@xtreamwayz the next release 4.0 would address this issue. The namespace will be Zend\PHPDI\Config.
Thank you for your feedback.

**Comment by elie29** [comment]
@xtreamwayz v4.0.0 has been released with a migration docs. On which branch should I create the pull request in order to use ^4.0 instead of ^3.0?

**Comment by xtreamwayz** [comment]
Oh, that's great. Thank you very much.

You can create a PR on the develop branch please.

**Comment by elie29** [comment]
@xtreamwayz ok thank you.
