### ISSUE TITLE
Support writing proxy classes to files

### ISSUE THREAD

**Issue by karsten-sbs** [elie29/zend-di-config#49]
In my project I need to use a lazy injection. I defined it as
<pre>
'dependencies' => [
        'services' => [
            Foo::class => DI\create(Foo::class)->constructor(DI\get(Bar::class))->lazy(),
        ],
        ...
</pre>
and it's working fine. However, in production mode I'd like to have the generated proxy class written to a file as described in https://php-di.org/doc/lazy-injection.html#optimizing-performances Could you please add support for that?

**Comment by elie29** [comment]
Hey @karsten-sbs, I will check this and add enable proxy, thx for your feedback

**Comment by karsten-sbs** [comment]
Thanks, would be really nice.

**Comment by elie29** [comment]
@karsten-sbs I made the modification on enable-proxy branch, could you test it?

**Comment by karsten-sbs** [comment]
Thank you! Yes, it works nicely.

**Comment by elie29** [comment]
Great, I will add some tests and release a new version
