### ISSUE TITLE
Container compilation and delegators

### ISSUE THREAD

**Issue by karsten-sbs** [elie29/zend-di-config#52]
I use several delegators in my project and if I define Config::DI_CACHE_PATH I get the error <pre>Cannot compile closures which import variables using the `use` keyword</pre> as mentioned in issue #45. The solution mentioned there isn't practicable in my case. I'd like to propose the following change to the Config class which eliminates the problem with the use keyword (and allows for type hinting the parameters):
```php
                $current                      =
                    factory(function (ContainerInterface $container, RequestedEntry $requestedEntry, string $delegator, string $previous, string $name) {
                        $factory  = new $delegator();
                        $callable = function () use ($previous, $container) {
                            return $container->get($previous);
                        };
                        return $factory($container, $name, $callable);
                    })->parameter('delegator', $delegator)
                      ->parameter('previous', $previous)
                      ->parameter('name', $name);
```

**Comment by elie29** [comment]
@karsten-sbs could you make the change and create a PR please? thx

**Comment by karsten-sbs** [comment]
Happy New Year, @elie29! I created a PR with my global account.

**Comment by elie29** [comment]
@karsten-sbs happy new year, I will check it as soon as possible. Thank you
